/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cajero;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julian Polanco
 */
public class interfazCuentasUsuario extends javax.swing.JFrame {

    public static String dato;
    public static String nombre2;
    /**
     * Creates new form interfazCuentasUsuario
     */
    public interfazCuentasUsuario() {
        initComponents();
        mostrarDatos();
        setLocationRelativeTo(null);
        nombre.setText("Bienvenido "+nombre2);
        this.getContentPane().setBackground(new Color(254, 244, 232));
    }
    
     void mostrarDatos(){
            DefaultTableModel cuentas = new DefaultTableModel();//instancia de tabla
            cuentas.addColumn("#");
            cuentas.addColumn("Documento");
            cuentas.addColumn("Numero de cuenta");
            tbCuentas.setModel(cuentas);
            String [] datos = new String [3];
            try{
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM cuenta WHERE numDoc="+dato+"");                                  
                int i=0;
                while (rs.next()){
                    i++;
                    datos[0]=i+"";
                    datos[1]=rs.getString(1);
                    datos[2]=rs.getString(2);
                    cuentas.addRow(datos);
                }
            }catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCuentas = new javax.swing.JTable();
        botonOcho = new javax.swing.JButton();
        botonNueve = new javax.swing.JButton();
        botonCero = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonUno = new javax.swing.JButton();
        botonCorregir = new javax.swing.JButton();
        botonDos = new javax.swing.JButton();
        botonContinuar = new javax.swing.JButton();
        botonTres = new javax.swing.JButton();
        botonCuatro = new javax.swing.JButton();
        botonCinco = new javax.swing.JButton();
        botonSeis = new javax.swing.JButton();
        botonSiete = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setText("Seleccione una de sus cuentas para continuar");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajero/twitter_header_photo_1.png"))); // NOI18N

        tbCuentas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbCuentas.setGridColor(new java.awt.Color(254, 244, 232));
        jScrollPane2.setViewportView(tbCuentas);

        botonOcho.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonOcho.setText("8");
        botonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOchoActionPerformed(evt);
            }
        });

        botonNueve.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonNueve.setText("9");
        botonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNueveActionPerformed(evt);
            }
        });

        botonCero.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCero.setText("0");
        botonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCeroActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(255, 0, 0));
        botonCancelar.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setPreferredSize(new java.awt.Dimension(207, 51));

        botonUno.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonUno.setText("1");
        botonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUnoActionPerformed(evt);
            }
        });

        botonCorregir.setBackground(new java.awt.Color(255, 255, 51));
        botonCorregir.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCorregir.setText("Corregir");
        botonCorregir.setPreferredSize(new java.awt.Dimension(207, 51));
        botonCorregir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCorregirActionPerformed(evt);
            }
        });

        botonDos.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonDos.setText("2");
        botonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDosActionPerformed(evt);
            }
        });

        botonContinuar.setBackground(new java.awt.Color(51, 255, 51));
        botonContinuar.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonContinuar.setText("Continuar");
        botonContinuar.setPreferredSize(new java.awt.Dimension(207, 51));
        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarActionPerformed(evt);
            }
        });

        botonTres.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonTres.setText("3");
        botonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTresActionPerformed(evt);
            }
        });

        botonCuatro.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCuatro.setText("4");
        botonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuatroActionPerformed(evt);
            }
        });

        botonCinco.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonCinco.setText("5");
        botonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCincoActionPerformed(evt);
            }
        });

        botonSeis.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonSeis.setText("6");
        botonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeisActionPerformed(evt);
            }
        });

        botonSiete.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        botonSiete.setText("7");
        botonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSieteActionPerformed(evt);
            }
        });

        nombre.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        nombre.setToolTipText("");
        nombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                .addComponent(botonSiete)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonOcho)
                                        .addGap(6, 6, 6)
                                        .addComponent(botonNueve))
                                    .addComponent(botonCero))
                                .addGap(10, 10, 10)
                                .addComponent(botonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                .addComponent(botonCuatro)
                                .addGap(6, 6, 6)
                                .addComponent(botonCinco)
                                .addGap(6, 6, 6)
                                .addComponent(botonSeis)
                                .addGap(10, 10, 10)
                                .addComponent(botonCorregir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                                .addComponent(botonUno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonDos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonTres)
                                .addGap(10, 10, 10)
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(15, 15, 15)
                .addComponent(nombre)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonUno)
                    .addComponent(botonDos)
                    .addComponent(botonTres)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCuatro)
                    .addComponent(botonCinco)
                    .addComponent(botonSeis)
                    .addComponent(botonCorregir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSiete)
                    .addComponent(botonOcho)
                    .addComponent(botonNueve)
                    .addComponent(botonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCero)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOchoActionPerformed
        // TODO add your handling code here:
        String cuentaSel;
        cuentaSel = tbCuentas.getValueAt(7,2).toString();
        interfazInicio.cuenta=cuentaSel;
        consultarSaldo.cuenta1=cuentaSel;
        consultarMovimientos.cuentaU=cuentaSel;
        interfazInicio clave = new interfazInicio();
        clave.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonOchoActionPerformed

    private void botonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNueveActionPerformed
        // TODO add your handling code here:
        String cuentaSel;
        cuentaSel = tbCuentas.getValueAt(8,2).toString();
        interfazInicio.cuenta=cuentaSel;
        consultarMovimientos.cuentaU=cuentaSel;
        consultarSaldo.cuenta1=cuentaSel;
        interfazInicio clave = new interfazInicio();
        clave.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonNueveActionPerformed

    private void botonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCeroActionPerformed

    private void botonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUnoActionPerformed
        // TODO add your handling code here:
        String cuentaSel;
        cuentaSel = tbCuentas.getValueAt(0,2).toString();
        interfazInicio.cuenta=cuentaSel;
        cambioDeClave.cuentaUsu=cuentaSel;
        consultarSaldo.cuenta1=cuentaSel;
        consultarMovimientos.cuentaU=cuentaSel;
        consultarMovimientos.cuentaU=cuentaSel;
        interfazInicio clave = new interfazInicio();
        clave.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonUnoActionPerformed

    private void botonCorregirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCorregirActionPerformed
        // TODO add your handling code here:
        InterfazDocumento volver = new InterfazDocumento();
        volver.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_botonCorregirActionPerformed

    private void botonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDosActionPerformed
        // TODO add your handling code here:
        String cuentaSel;
        cuentaSel = tbCuentas.getValueAt(1,2).toString();
        interfazInicio.cuenta=cuentaSel;
        consultarSaldo.cuenta1=cuentaSel;
        cambioDeClave.cuentaUsu=cuentaSel;
        consultarMovimientos.cuentaU=cuentaSel;
        interfazInicio clave = new interfazInicio();
        clave.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonDosActionPerformed

    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarActionPerformed
        // TODO add your handling code here:
        int fila = tbCuentas.getSelectedRow();        
        String cuentaSel;
        cuentaSel = tbCuentas.getValueAt(fila,2).toString();
        interfazInicio.cuenta=cuentaSel;
        consultarMovimientos.cuentaU=cuentaSel;
        cambioDeClave.cuentaUsu=cuentaSel;
        consultarSaldo.cuenta1=cuentaSel;
        interfazInicio clave = new interfazInicio();
        interfazInicio.nombre = nombre2;
        clave.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonContinuarActionPerformed

    private void botonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTresActionPerformed
        // TODO add your handling code here:
        String cuentaSel;
        cuentaSel = tbCuentas.getValueAt(2,2).toString();
        interfazInicio.cuenta=cuentaSel;
        consultarSaldo.cuenta1=cuentaSel;
        cambioDeClave.cuentaUsu=cuentaSel;
        consultarMovimientos.cuentaU=cuentaSel;
        interfazInicio clave = new interfazInicio();
        clave.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonTresActionPerformed

    private void botonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuatroActionPerformed
        // TODO add your handling code here:
        String cuentaSel;
        cuentaSel = tbCuentas.getValueAt(3,2).toString();
        interfazInicio.cuenta=cuentaSel;
        cambioDeClave.cuentaUsu=cuentaSel;
        consultarSaldo.cuenta1=cuentaSel;
        consultarMovimientos.cuentaU=cuentaSel;
        interfazInicio clave = new interfazInicio();
        clave.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonCuatroActionPerformed

    private void botonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCincoActionPerformed
        // TODO add your handling code here:
       String cuentaSel;
        cuentaSel = tbCuentas.getValueAt(4,2).toString();
        interfazInicio.cuenta=cuentaSel;
        cambioDeClave.cuentaUsu=cuentaSel;
        consultarSaldo.cuenta1=cuentaSel;
        consultarMovimientos.cuentaU=cuentaSel;
        interfazInicio clave = new interfazInicio();
        clave.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonCincoActionPerformed

    private void botonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeisActionPerformed
        // TODO add your handling code here:
        String cuentaSel;
        cuentaSel = tbCuentas.getValueAt(5,2).toString();
        interfazInicio.cuenta=cuentaSel;
        cambioDeClave.cuentaUsu=cuentaSel;
        consultarMovimientos.cuentaU=cuentaSel;
        consultarSaldo.cuenta1=cuentaSel;
        interfazInicio clave = new interfazInicio();
        clave.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonSeisActionPerformed

    private void botonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSieteActionPerformed
        // TODO add your handling code here:
        String cuentaSel;
        cuentaSel = tbCuentas.getValueAt(6,2).toString();
        interfazInicio.cuenta=cuentaSel;
        cambioDeClave.cuentaUsu=cuentaSel;
        consultarSaldo.cuenta1=cuentaSel;
        consultarSaldo.cuenta1=cuentaSel;
        consultarMovimientos.cuentaU=cuentaSel;
        
        interfazInicio clave = new interfazInicio();
        clave.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonSieteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazCuentasUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazCuentasUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazCuentasUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazCuentasUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazCuentasUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCero;
    private javax.swing.JButton botonCinco;
    private javax.swing.JButton botonContinuar;
    private javax.swing.JButton botonCorregir;
    private javax.swing.JButton botonCuatro;
    private javax.swing.JButton botonDos;
    private javax.swing.JButton botonNueve;
    private javax.swing.JButton botonOcho;
    private javax.swing.JButton botonSeis;
    private javax.swing.JButton botonSiete;
    private javax.swing.JButton botonTres;
    private javax.swing.JButton botonUno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTable tbCuentas;
    // End of variables declaration//GEN-END:variables
conexion cc= new conexion();
       Connection cn = cc.conexion();
       
}
